apiVersion: v1
kind: Service
metadata:
  name: {{ include "izzymart.fullname" . }}-api
  labels:
    {{- include "izzymart.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "izzymart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
