apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "izzymart.fullname" . }}-gui
  labels:
    {{- include "izzymart.labels" . | nindent 4 }}
    app.kubernetes.io/component: gui
spec:
  {{- if not .Values.autoscaling.gui.enabled }}
  replicas: {{ .Values.replicaCount.gui }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "izzymart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "izzymart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "izzymart.serviceAccountName" . }}
      securityContext: {}
      containers:
      - name: gui
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
        image: "{{ .Values.image.gui.repository }}:{{ .Values.image.gui.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.gui.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources.gui | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
