apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "izzymart.fullname" . }}-mongodb
  labels:
    {{- include "izzymart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: {{ .Values.replicaCount.mongodb }}
  selector:
    matchLabels:
      {{- include "izzymart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "izzymart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - name: mongodb
          containerPort: 27017
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.resources.mongodb | nindent 12 }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        {{- if .Values.mongodb.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "izzymart.fullname" . }}-mongodb
        {{- else }}
        emptyDir: {}
        {{- end }}
