apiVersion: v1
kind: Service
metadata:
  name: {{ include "izzymart.fullname" . }}-mongodb
  labels:
    {{- include "izzymart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.service.mongodb.type }}
  ports:
    - port: {{ .Values.service.mongodb.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "izzymart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
